export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const FILTER_BY_PRICE_DESCENDING = "FILTER_BY_PRICE_DESCENDING";
export const FILTER_BY_PRICE_ASCENDING = "FILTER_BY_PRICE_ASCENDING";
export const FILTER_BY_DEFAULT = "FILTER_BY_DEFAULT";